slurmify submit-parametric-array \
  --account CGAI24022 \
  --job-name annotate \
  --script-path slurm_jobs/annotate_fixed_sigma.py \
  --time-limit 01:00:00 \
   --parameter "dataset:cifar" \
  --parameter "dataset_path:/scratch/07362/gdaras/datasets/cifar10-32x32.zip" \
  --parameter "inference_noise_config:blurs0_6" \
  --parameter "corruption_probability:0.9" \
  --parameter "min_fixed_sigma:1.0,0.8,0.6,0.4,0.2,0.1" \
  --parameter "max_fixed_sigma:0.0" \
  --parameter "save_only_clean:False" \
  --partition "gg" \
  --nodes=32 \
  --check_worthiness=False \
  --max-resubmissions=0