slurmify submit-parametric-array \
  --account CGAI24022 \
  --job-name annotate_cifar_reg_cls \
  --script-path slurm_jobs/annotate_reg.py \
  --time-limit 06:00:00 \
  --parameter "dataset:cifar" \
  --parameter "dataset_path:/scratch/07362/gdaras/datasets/cifar10-32x32.zip" \
  --parameter "corruption_probability:0.9" \
  --parameter "training_noise_config:blurs0_8" \
  --parameter "inference_noise_config:blurs0_8" \
  --partition "gh" \
  --nodes=64 \
  --check_worthiness=False \
  --max-resubmissions=0